### ISSUE TITLE
PyCharm Prof. doesn't recognize Python 3.10

### ISSUE THREAD

**Issue by sebastian-philipp** [flathub/com.jetbrains.PyCharm-Professional#56]
# Steps to Reproduce

1. open project

2. add 3.10 interpreter

# Actual Result

```
2022-05-19 15:11:56,048 [  45893]   WARN - #c.j.p.s.PySdkUtil - Cannot run program "/home/sebastian/Repos/...snip.../venv/bin/python" (in directory "/home/sebastian/Repos/...snip.../venv/bin"): error=2, Datei oder Verzeichnis nicht gefunden
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "/home/sebastian/Repos/...snip.../venv/bin/python" (in directory "/home/sebastian/Repos/...snip.../venv/bin"): error=2, Datei oder Verzeichnis nicht gefunden
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:362)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:92)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:45)
	at com.intellij.execution.process.CapturingProcessHandler.<init>(CapturingProcessHandler.java:20)
	at com.jetbrains.python.sdk.PySdkUtil.getProcessOutput(PySdkUtil.java:124)
	at com.jetbrains.python.sdk.PySdkUtil.getProcessOutput(PySdkUtil.java:99)
	at com.jetbrains.python.sdk.PythonSdkType.getSysPathsFromScript(PythonSdkType.java:463)
	at com.jetbrains.python.sdk.PythonSdkType.getSysPath(PythonSdkType.java:449)
	at com.jetbrains.python.sdk.PythonSdkUpdater.evaluateSysPath(PythonSdkUpdater.java:635)
	at com.jetbrains.python.sdk.PythonSdkUpdater.updateLocalSdkVersionAndPaths(PythonSdkUpdater.java:411)
	at com.jetbrains.python.sdk.PythonSdkUpdater.lambda$updateVersionAndPathsSynchronouslyAndScheduleRemaining$0(PythonSdkUpdater.java:293)
	at com.intellij.openapi.progress.impl.CoreProgressManager$1.run(CoreProgressManager.java:270)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$8(CoreProgressManager.java:526)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:83)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Cannot run program "/home/sebastian/Repos/...snip.../venv/bin/python" (in directory "/home/sebastian/Repos/...snip.../venv/bin"): error=2, Datei oder Verzeichnis nicht gefunden
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:438)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:352)
	... 32 more
Caused by: java.io.IOException: error=2, Datei oder Verzeichnis nicht gefunden
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 35 more
2022-05-19 15:11:56,050 [  45895]   INFO - #c.j.p.s.PythonSdkType - Exit code -1
2022-05-19 15:11:56,050 [  45895]   INFO - #c.j.p.s.PythonSdkType - Cannot run program "/home/sebastian/Repos/...snip.../venv/bin/python" (in directory "/home/sebastian/Repos/...snip.../venv/bin"): error=2, Datei oder Verzeichnis nicht gefunden
2022-05-19 15:11:56,052 [  45897]   WARN - #c.j.p.s.PythonSdkUpdater - Error while evaluating path and version: 
com.jetbrains.python.sdk.InvalidSdkException: Failed to determine Python's sys.path value:
STDOUT: 
STDERR: Cannot run program "/home/sebastian/Repos/...snip.../venv/bin/python" (in directory "/home/sebastian/Repos/...snip.../venv/bin"): error=2, Datei oder Verzeichnis nicht gefunden
	at com.jetbrains.python.sdk.PythonSdkType.getSysPathsFromScript(PythonSdkType.java:466)
	at com.jetbrains.python.sdk.PythonSdkType.getSysPath(PythonSdkType.java:449)
	at com.jetbrains.python.sdk.PythonSdkUpdater.evaluateSysPath(PythonSdkUpdater.java:635)
	at com.jetbrains.python.sdk.PythonSdkUpdater.updateLocalSdkVersionAndPaths(PythonSdkUpdater.java:411)
	at com.jetbrains.python.sdk.PythonSdkUpdater.lambda$updateVersionAndPathsSynchronouslyAndScheduleRemaining$0(PythonSdkUpdater.java:293)
	at com.intellij.openapi.progress.impl.CoreProgressManager$1.run(CoreProgressManager.java:270)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$8(CoreProgressManager.java:526)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:83)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-05-19 15:12:20,599 [  70444]   INFO - #c.j.p.p.PyPackageManagerImpl - Running packaging tool: /home/sebastian/Repos/...snip.../venv/bin/python /app/extra/plugins/python/helpers/packaging_tool.py list
2022-05-19 15:12:20,601 [  70446]   WARN - #c.i.w.p.InstalledPackagesPanel - Cannot run program "/home/sebastian/Repos/...snip.../venv/bin/python" (in directory "/home/sebastian/Repos/...snip.../venv/bin"): error=2, Datei oder Verzeichnis nicht gefunden
```

I can assure you, the file is there! And /bin/python3.10 is there as well.

Note, I **cannot** reproduce this with the standard (non-flatpak) version. 

https://youtrack.jetbrains.com/issue/PY-54304/Flatpak-PyCharm-Prof-doesn-t-recognize-Python-3-10 was closed due to they're not maintaining PyCharm Prof
![Screenshot_20220519_151141](https://user-images.githubusercontent.com/2574405/169307839-58db7a9b-8b93-4ad5-8ca7-db91a123fa18.png)
![Screenshot_20220519_151201](https://user-images.githubusercontent.com/2574405/169307843-0a71a348-09ae-4468-b74b-129f4f0aa258.png)
![Screenshot_20220519_151211](https://user-images.githubusercontent.com/2574405/169307844-d8a71345-2b49-47b6-821b-f3fbe917e321.png)
![Screenshot_20220519_151338](https://user-images.githubusercontent.com/2574405/169307846-df7d9c27-4b51-4dd2-a458-b3646ee00c0d.png)
![Screenshot_20220519_152206](https://user-images.githubusercontent.com/2574405/169307850-3aa98017-ba49-444d-b03a-e222a658b9f3.png)

**Comment by johanfleury** [comment]
Flatpak applications run in sandboxes and don’t have access to the host filesystem by default. PyCharm relies on the `org.freedesktop.Platform` runtime version 21.08 which ships with Python 3.9. The `/usr/bin/python3.10` file you’re seeing is from your host filesystem.

> https://youtrack.jetbrains.com/issue/PY-54304/Flatpak-PyCharm-Prof-doesn-t-recognize-Python-3-10 was closed due to they're not maintaining PyCharm Prof

Yes, as stated on FlatHub this application is “not verified by, affiliated with, or supported by JetBrains s.r.o.”.

Regarding the link to the issue tracker: I basically forked PyCharm Community Flatpak when I created PCP and I didn’t pay attention to that. I’ll update it as soon as possible.

**Comment by freeseacher** [comment]
Python 3.10 is now default python since we moved to newer platform version
